{
 "title": "rbd-mirror-snapshot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Overall Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rbd_mirror_snapshot_health)"
    }
   ]
  },
  {
   "title": "Replication Schedules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rbd_mirror_snapshot_schedules)"
    }
   ]
  },
  {
   "title": "Pools Replicated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(rbd_mirror_snapshot_health)"
    }
   ]
  },
  {
   "title": "Images Replicated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rbd_mirror_snapshot_image_state)"
    }
   ]
  },
  {
   "title": "Time to Gather Data",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "secs" }
   ],
   "targets": [
    {
     "expr": "rbd_mirror_snapshot_scrape_seconds",
     "legendFormat": "scrape time"
    }
   ]
  },
  {
   "title": "Total of Replicated Images by Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rbd_mirror_snapshot_image_state) by(pool_name)",
     "legendFormat": "{{pool_name}}"
    }
   ]
  },
  {
   "title": "rbd-mirror Snapshot Relationships",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rbd_mirror_snapshot_health * on(pool_name) group_right(health) rbd_mirror_snapshot_metadata"
    }
   ]
  },
  {
   "title": "rbd-mirror States",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"replaying\"})",
     "legendFormat": "replaying"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"unknown\"})",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"error\"})",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"starting_replay\"})",
     "legendFormat": "starting replay"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"stopping_replay\"})",
     "legendFormat": "stopping_replay"
    }
   ]
  },
  {
   "title": "Replication State over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"replaying\"})",
     "legendFormat": "replaying"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"error\"})",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"unknown\"})",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"starting_replay\"})",
     "legendFormat": "starting"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"stopping_replay\"})",
     "legendFormat": "Stopping"
    },
    {
     "expr": "sum(rbd_mirror_snapshot_image_state{status=\"stopped\"})",
     "legendFormat": "stopped"
    }
   ]
  }
 ]
}